### ISSUE TITLE
Histogram Metric

### ISSUE THREAD

**Issue by RennanAugusto** [marcobreveglieri/prometheus-client-delphi#2]
Hello Marco Breveglieri,
I trust this message finds you well.

I am writing to inform you that I have completed the implementation of the histogram metric for prometheus-client-delphi. I am eager to contribute and believe that my work can add value to the project.

May I kindly request access to the repository to open a pull request? This will allow you to review the code and provide any necessary feedback or suggestions for improvement.

I appreciate your time and consideration.

Best regards,
Rennan Augusto

**Comment by marcobreveglieri** [comment]
Hi @RennanAugusto,
thank you very much for your request to participate and submit your contribution! 💘

You don't need any access to the repository: you can just create a fork and make the changes needed to your repo.

Here you can find more info about this process:
https://opensource.com/article/19/7/create-pull-request-github

Thanks again!
Marco.

**Comment by RennanAugusto** [comment]
Hi @marcobreveglieri.

Thank you for your help; this is still a bit confusing for me as it's the first time I've contributed to something open source.

I forked the repository and created the pull request.

Best regards,
Rennan

**Comment by marcobreveglieri** [comment]
Hi @RennanAugusto,
don't worry at all because I am quite new at GitHub contributions too. 😅

I see the new pull request pending.
I will be a little busy this week but I am planning to give a deep look to your code ASAP!

Thanks for your really valuable contribution!

I'll also add a new section to the README file in order to give the right visibility to those who have contributed to the project.

Best regards,
  Marco.

**Comment by Tuxino** [comment]
Hi Marco Breveglieri,

Just wondering if you have had a chance to look over the code that was comitted a while back? Our team is actually looking to implement the histogram metric into one of our Delphi projects and this would be invaluable for us. Up until now I wasn't aware that any work had been done on this metric until I noticed the pull request!

Special thanks to Rennan for the implementation!

Regards,
David

**Comment by marcobreveglieri** [comment]
Hi @Tuxino,
I took a look at Rennan's pull request for the Histogram Metric some time ago, but when compared to other client implementations it seems to be "out of standard" or not quite what users expect in terms of form and functionality.

I need to look into this further, but unfortunately I haven't had time to do so yet due to work.

I hope to take a look in the immediate future, so I can close this open issue.

Sorry about that! 😳

**Comment by Tuxino** [comment]
All good - thanks for getting back to me so quickly and letting me know

**Comment by fastbike** [comment]
Hi @RennanAugusto  @marcobreveglieri 
I've taken a look at the the pull request and can see there is some adjustment required to meet the Prometheus protocol and the coding standards used in this repo.
We're looking to integrate Prometheus into a DMVC Framework app - would you be OK if I had a go at refactoring the code in the PR ?
The other metric missing is the "Summary"

**Comment by RennanAugusto** [comment]
Hi @fastbike  @marcobreveglieri 

I had implemented the histogram metric using some other example clients written in different languages.

When I did it, I remember testing it, and it seemed to work well; maybe a thing or two slipped through.

In the end, I haven't used the histogram metric in my DMVC project yet.

@fastbike   if you want to change anything in the PR, I have no problem with that, or if you’d like to list the things you saw that need to be changed here, I can take a look this week.

Best regards!

**Comment by marcobreveglieri** [comment]
Hi @fastbike @RennanAugusto, 
I must sincerely thank you for your support and interest in implementing the missing metric(s), really appreciated.

Believe me, I am truly sorry that I am not able (at this time) to give you all the support, especially a well-grounded and accurated feedback about your doubts, requests and implementations.

That said, I've absolutely no problem or restrictions regarding the modification of any PR or the proposal of other contributions regarding missing implementations; indeed I would be very happy to welcome proposals of implementations and feedback regarding their goodness coming from someone who can test at some degree the features in real use cases.

@fastbike if you want to give a try to @RennanAugusto PR and check if it suits your needs, maybe we can integrate that to the library and merge it to the main branch, because I could have done an oversight: I remember seeing some "time related" implementation for Histogram metrics in some client (don't remember which one and in which way) but I must say that client libraries for different languages implements things in very different manners. If @RennanAugusto implementation meets your expectations @fastbike, and you can confirm that, I would merge the PR without further checks. :)

It's better to have an implementation that works at this point and maybe make it better and evolving with feedbacks from Delphi developers/users, putting comparisons to other libraries aside (which could be my fault). :)

Thanks a lot again for your precious support and all the patience! :)
Marco.

**Comment by fastbike** [comment]
@marcobreveglieri  all good.  I am looking at the YT video where the creator of Prometheus explains the thinking underlying the Histogram metric.
https://www.youtube.com/watch?v=yYbXak-1hew
I will submit a PR once I have completed the testing (next week)

**Comment by HealthOneNZ-DevManager** [comment]
I have refactored the Histogram to follow the intent of the Prometheus project. In particular the child object is used to created user defined labelled metrics. The labels created from the buckets are no managed automatically, and Buckets have to be provided at Create time.
Some examples of use have been added to the demo project and unit tests added.
@marcobreveglieri  I will create a PR

**Comment by marcobreveglieri** [comment]
Hi @HealthOneNZ (are you the same or a colleague of @fastbike?),
I've seen your message and the pull request. Very, very interesting!

I am busy till the next week (working on a conference where I'll talk about Delphi!), then I will take time to fully review and integrate the pull request on main branch.

I will find the way to highlight all your contributes because I really appreciate the efforts made by the community to integrate a very important feature into the library! 💘

Thanks again! 🤗

**Comment by fastbike** [comment]
Hi one is a private account, the other one I use for work. We just noticed there needs to be one more change in Prometheus.SimpleCollector.pas to promote the FLock object so it is accessible from the descendant classes.
```
  TSimpleCollector<TChild: class> = class abstract(TCollector)
  strict private
    FChildren: TDictionary<TLabelValues, TChild>;
    FHelp: string;
    FLabelNames: TLabelNames;
    FLock: TObject;
    FName: string;
    procedure InitializeNoLabelChildIfNeeded();
    function GetChildrenCount: Integer;
  strict protected
    function CreateChild: TChild; virtual;
    procedure EnumChildren(ACallback: TChildrenCallback<TChild>);
    function GetNoLabelChild: TChild;
  public
```
becomes
```
 TSimpleCollector<TChild: class> = class abstract(TCollector)
  private
    FChildren: TDictionary<TLabelValues, TChild>;
    FHelp: string;
    FLabelNames: TLabelNames;
    FName: string;
    procedure InitializeNoLabelChildIfNeeded();
    function GetChildrenCount: Integer;
  protected
    FLock: TObject;
    function CreateChild: TChild; virtual;
    procedure EnumChildren(ACallback: TChildrenCallback<TChild>);
    function GetNoLabelChild: TChild;
  public
```

**Comment by marcobreveglieri** [comment]
> Hi one is a private account, the other one I use for work. We just noticed there needs to be one more change in Prometheus.SimpleCollector.pas to promote the FLock object so it is accessible from the descendant classes.

Thanks! I will keep in mind this aspect too. :)

**Comment by fastbike** [comment]
Crikey, one of my colleagues just pointed out the logic in the histogram was 180 degrees out !
I have fixed that and updated the tests. I will update the PR.

**Comment by fastbike** [comment]
Another two small changes committed to my fork, these were noticed during peer review

**Comment by marcobreveglieri** [comment]
Histogram metric code has been reviewed and integrated to the main branch in this commit:
https://github.com/marcobreveglieri/prometheus-client-delphi/commit/5575f2ace5e3031184cc0cb8f3d2f882b86d537d

What can I say... thank you so much to all the participants in this issue who have given a truly precious and fundamental contribution to the project and the integration of this feature! 💞
